name: cfu-common
channels:
  - defaults
  - litex-hub
dependencies:
  - litex-hub::gcc-riscv32-elf-newlib
  - litex-hub::dfu-util
  - litex-hub::flterm
  - litex-hub::openocd
  - litex-hub::verilator
  - litex-hub::nextpnr-nexus
  - litex-hub::nextpnr-ecp5
  - litex-hub::nextpnr-ice40
  - litex-hub::iceprog
# Temporarily pin Yosys until symbiflow-yosys-plugins catches up
  - litex-hub::yosys=0.33_11_g31ee566ec=20230724_080446_py37
  - litex-hub::symbiflow-yosys-plugins
  - libevent
  - json-c
  - python=3.7
  - pip
  - pip:
    - -r ./requirements.txt
